#!/bin/sh

./gradlew ktlintCheck
if [ $? -ne 0 ]; then
  echo "ktlint checks failed. Please fix the issues before committing."
  exit 1
fi

./gradlew detekt
if [ $? -ne 0 ]; then
  echo "detekt checks failed. Please fix the issues before committing."
  exit 1
fi

exit 0
